# Generated by Django 2.0.3 on 2018-03-09 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsreel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='date_published',
            new_name='pub_date',
        ),
    ]
