# Generated by Django 2.0.3 on 2018-03-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsreel', '0002_auto_20180309_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='pjj', max_length=200),
            preserve_default=False,
        ),
    ]
